version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:12.18

workflows:
  main:
    jobs:
      - install_dependencies:
          filters:
            tags:
              only: /^v.*/
      - lint:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /^v.*/
      - publish:
          context: hq-global
          requires:
            - lint
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  install_dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate NPM
          command: |
            npm set registry https://$NPM_REGISTRY
            echo "//$NPM_REGISTRY/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish
          command: npm publish
      - run:
          name: Notify Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
              -d '{"text":"Published $CIRCLE_PROJECT_REPONAME@$CIRCLE_TAG to registry $NPM_REGISTRY"}' \
              $SLACK_NOTIFY_WEBHOOK
